### ISSUE TITLE
Implement simple pages for genotypes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/pombase-chado-json#173]

**Comment by kimrutherford** [comment]
Done

**Comment by ValWood** [comment]
What's this?

**Comment by kimrutherford** [comment]
It's a hacky way to (hopefully) improve our search rankings.  Our pages take a second or more to load and require Javascript to work.  Google search isn't keen on either of those things.  Some of the other search engines can't cope with Javascript at all.

So when Google or one of the other major search engines crawls pombase.org they get a simplified version of the gene, term, publication and now genotype pages.  The simple versions have no Javascript and look awful but are very quick and are easy to index.

You can see what they get if you put "/simple" in the URL, like: https://www.pombase.org/simple/gene/SPBC660.14
(screenshot below)

Or: https://www.pombase.org/simple/reference/PMID:10521402

I implemented this for term, gene and publication pages in 2019 but I've only just got around to doing the same thing for the genotype pages on Friday (with a bug fix on Saturday :-) )

I haven't done a lot of optimisation of what appears on the pages but they seem to be doing OK for Google searches.

The snippet shown in the Google search results is from the "simple" pages:

![image](https://github.com/pombase/pombase-chado-json/assets/90474/6551dbfb-97e8-407a-8317-10bf83f5d6bd)

--------------------------

Here's a screenshot of the "simple" version of `mik1`:

![image](https://github.com/pombase/pombase-chado-json/assets/90474/45487e72-bd37-4a8e-9a8a-3ea7ebf8b0a9)

**Comment by ValWood** [comment]
Neat, I thought it was some new page type I had missed!
